---
abstract: 'an interface to the Pixelletter API'
author:
  - 'Robin Clarke <rcl@robinclarke.net>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Pixelletter
no_index:
  directory:
    - t
    - inc
requires:
  File::Util: 0
  LWP::UserAgent: 0
  Locale::Country: 0
version: 0.2
